# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build image

on: [push, workflow_dispatch]

env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: todomvc

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v1.2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Login Github Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u owner --password-stdin

      - name: Build image
        run: |
          ./mvnw -B --file pom.xml spring-boot:build-image -Dspring-boot.build-image.imageName=docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${{ env.SHA }}

      - name: Push image to Github Registry
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${{ env.SHA }}

      - name: Tag and push image as latest
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker tag docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${{ env.SHA }} docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:latest
          docker push docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:latest
